// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniWallet.Database.Persistence;

namespace OmniWallet.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191005013942_CriadoTabelaPais")]
    partial class CriadoTabelaPais
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.Pais", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("DDI")
                        .IsRequired()
                        .HasColumnName("ddi")
                        .HasMaxLength(4);

                    b.Property<string>("ISO2")
                        .HasColumnName("iso2")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("ISO3")
                        .HasColumnName("iso3")
                        .IsFixedLength(true)
                        .HasMaxLength(3);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_paises");

                    b.ToTable("paises");
                });

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("IdPessoaFisica")
                        .HasColumnName("id_pessoa_fisica");

                    b.Property<int?>("IdPessoaJuridica")
                        .HasColumnName("id_pessoa_juridica");

                    b.HasKey("Id")
                        .HasName("pk_pessoas");

                    b.HasIndex("IdPessoaFisica")
                        .IsUnique()
                        .HasName("ix_pessoas_id_pessoa_fisica");

                    b.HasIndex("IdPessoaJuridica")
                        .IsUnique()
                        .HasName("ix_pessoas_id_pessoa_juridica");

                    b.ToTable("pessoas");
                });

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.PessoaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(32);

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnName("sobrenome")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_pessoas_fisicas");

                    b.ToTable("pessoas_fisicas");
                });

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.PessoaJuridica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnName("cnpj")
                        .IsFixedLength(true)
                        .HasMaxLength(14);

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnName("dominio")
                        .HasMaxLength(10);

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnName("nome_fantasia")
                        .HasMaxLength(255);

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnName("razao_social")
                        .HasMaxLength(255);

                    b.HasKey("Id")
                        .HasName("pk_pessoas_juridicas");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasName("ix_pessoas_juridicas_cnpj");

                    b.HasIndex("Dominio")
                        .IsUnique()
                        .HasName("ix_pessoas_juridicas_dominio");

                    b.HasIndex("RazaoSocial")
                        .IsUnique()
                        .HasName("ix_pessoas_juridicas_razao_social");

                    b.ToTable("pessoas_juridicas");
                });

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ativo")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(255);

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnName("email_confirmado");

                    b.Property<DateTime>("MembroDesde")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("membro_desde")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnName("senha_hash")
                        .IsFixedLength(true)
                        .HasMaxLength(64);

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnName("senha_salt")
                        .IsFixedLength(true)
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("ix_usuarios_email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.Pessoa", b =>
                {
                    b.HasOne("OmniWallet.Database.Contracts.Persistence.Domain.PessoaFisica", "PessoaFisica")
                        .WithOne("Pessoa")
                        .HasForeignKey("OmniWallet.Database.Contracts.Persistence.Domain.Pessoa", "IdPessoaFisica")
                        .HasConstraintName("fk_pessoas_pessoas_fisicas_id_pessoa_fisica")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniWallet.Database.Contracts.Persistence.Domain.PessoaJuridica", "PessoaJuridica")
                        .WithOne("Pessoa")
                        .HasForeignKey("OmniWallet.Database.Contracts.Persistence.Domain.Pessoa", "IdPessoaJuridica")
                        .HasConstraintName("fk_pessoas_pessoas_juridicas_id_pessoa_juridica")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
