// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniWallet.Database.Persistence;

namespace OmniWallet.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191004232804_CriadoTabelaPessoasFisicas")]
    partial class CriadoTabelaPessoasFisicas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.PessoaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(32);

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnName("sobrenome")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("pk_pessoas_fisicas");

                    b.ToTable("pessoas_fisicas");
                });

            modelBuilder.Entity("OmniWallet.Database.Contracts.Persistence.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ativo")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(255);

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnName("email_confirmado");

                    b.Property<DateTime>("MembroDesde")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("membro_desde")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnName("senha_hash")
                        .IsFixedLength(true)
                        .HasMaxLength(64);

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnName("senha_salt")
                        .IsFixedLength(true)
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("ix_usuarios_email");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
